Fix build error because undeclared ushort type
Compiling the engine fails with this error:

src/opcodes.c: In function 'cchartmap':
src/opcodes.c:6228:34: error: 'ushort' undeclared (first use in this function); did you mean 'qsort'?
 6228 |                 u16 word_span = (ushort)(aligned_max - (min_x & 0xfff0)) >> 4;
      |                                  ^~~~~~
      |                                  qsort

Attached patch fixes the error.